### PR TITLE
Use ansible local

### PR DESCRIPTION
**Pull request by AnwarYagoub**
fixing issues with pull request #15

### CODE REVIEW

**Comment by AnwarYagoub** [comment]
This is the pull request to fix it all :)

**Comment by smartbit** [comment]
I'll take a look.

**Comment by smartbit** [comment]
I tested above and works with me. What's your take? 

Could you take a look at `tail -12 /root/VirtualBox\ VMs/labipa/Logs/VBox.log`? Maybe it helps with `ansible_dns.nameservers[0]`

**Comment by AnwarYagoub** [comment]
Everything looks fine me but my own problem was with `ansible_dns.nameservers[0]` I will test it again.

mean time I will accept this pull request & close pull request #15

**Pull request merged**
